/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UpdatesImport } from './routes/updates'
import { Route as SignupImport } from './routes/signup'
import { Route as ProfileImport } from './routes/profile'
import { Route as MessagesImport } from './routes/messages'
import { Route as LoginImport } from './routes/login'
import { Route as ChatsImport } from './routes/chats'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileUserIdImport } from './routes/profile/$userId'
import { Route as ChatUserIdImport } from './routes/chat/$userId'

// Create/Update Routes

const UpdatesRoute = UpdatesImport.update({
  path: '/updates',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const MessagesRoute = MessagesImport.update({
  path: '/messages',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ChatsRoute = ChatsImport.update({
  path: '/chats',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUserIdRoute = ProfileUserIdImport.update({
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)

const ChatUserIdRoute = ChatUserIdImport.update({
  path: '/chat/$userId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesImport
      parentRoute: typeof rootRoute
    }
    '/chat/$userId': {
      id: '/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/chat/$userId'
      preLoaderRoute: typeof ChatUserIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdImport
      parentRoute: typeof ProfileImport
    }
  }
}

// Create and export the route tree

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/updates': typeof UpdatesRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/updates': typeof UpdatesRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/updates': typeof UpdatesRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/login'
    | '/messages'
    | '/profile'
    | '/signup'
    | '/updates'
    | '/chat/$userId'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/login'
    | '/messages'
    | '/profile'
    | '/signup'
    | '/updates'
    | '/chat/$userId'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/login'
    | '/messages'
    | '/profile'
    | '/signup'
    | '/updates'
    | '/chat/$userId'
    | '/profile/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SignupRoute: typeof SignupRoute
  UpdatesRoute: typeof UpdatesRoute
  ChatUserIdRoute: typeof ChatUserIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SignupRoute: SignupRoute,
  UpdatesRoute: UpdatesRoute,
  ChatUserIdRoute: ChatUserIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chats",
        "/login",
        "/messages",
        "/profile",
        "/signup",
        "/updates",
        "/chat/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chats": {
      "filePath": "chats.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/messages": {
      "filePath": "messages.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx",
      "children": [
        "/profile/$userId"
      ]
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/updates": {
      "filePath": "updates.tsx"
    },
    "/chat/$userId": {
      "filePath": "chat/$userId.tsx"
    },
    "/profile/$userId": {
      "filePath": "profile/$userId.tsx",
      "parent": "/profile"
    }
  }
}
ROUTE_MANIFEST_END */
